# Generated by Django 5.1.3 on 2025-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_energy_consumption_alter_device_status_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='energy6',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='energy',
            name='energy7',
            field=models.FloatField(default=100),
        ),
    ]
