# Generated by Django 5.1.3 on 2025-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_energy_energy6_energy_energy7'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activity_log',
            field=models.JSONField(default=list),
        ),
    ]
