# Generated by Django 5.1.3 on 2025-02-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='input_source',
            field=models.CharField(choices=[('HDMI', 'HDMI'), ('Cable', 'Cable'), ('Stream', 'Stream')], default='HDMI', max_length=10),
        ),
    ]
