# Generated by Django 5.1.3 on 2025-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_activity_log_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='energy_consumption',
            field=models.FloatField(default=0),
        ),
    ]
