# Generated by Django 5.1.3 on 2025-02-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_energy_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconditioner',
            name='base_energy',
            field=models.FloatField(default=60000),
        ),
        migrations.AddField(
            model_name='airpurifier',
            name='base_energy',
            field=models.FloatField(default=30000),
        ),
        migrations.AddField(
            model_name='blinds',
            name='base_energy',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='coffeemaker',
            name='base_energy',
            field=models.FloatField(default=3000),
        ),
        migrations.AddField(
            model_name='fridge',
            name='base_energy',
            field=models.FloatField(default=150000),
        ),
        migrations.AddField(
            model_name='light',
            name='base_energy',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='oven',
            name='base_energy',
            field=models.FloatField(default=20000),
        ),
        migrations.AddField(
            model_name='roomba',
            name='base_energy',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='smartlock',
            name='base_energy',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='speaker',
            name='base_energy',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='television',
            name='base_energy',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='base_energy',
            field=models.FloatField(default=20000),
        ),
        migrations.AddField(
            model_name='washingmachine',
            name='base_energy',
            field=models.FloatField(default=100000),
        ),
    ]
