# Generated by Django 5.1.3 on 2025-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_airconditioner_base_energy_airpurifier_base_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='base_energy',
            field=models.FloatField(default=216),
        ),
        migrations.AlterField(
            model_name='airpurifier',
            name='base_energy',
            field=models.FloatField(default=108),
        ),
        migrations.AlterField(
            model_name='blinds',
            name='base_energy',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='coffeemaker',
            name='base_energy',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='base_energy',
            field=models.FloatField(default=540),
        ),
        migrations.AlterField(
            model_name='light',
            name='base_energy',
            field=models.FloatField(default=180),
        ),
        migrations.AlterField(
            model_name='oven',
            name='base_energy',
            field=models.FloatField(default=72),
        ),
        migrations.AlterField(
            model_name='roomba',
            name='base_energy',
            field=models.FloatField(default=35),
        ),
        migrations.AlterField(
            model_name='smartlock',
            name='base_energy',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='base_energy',
            field=models.FloatField(default=36),
        ),
        migrations.AlterField(
            model_name='television',
            name='base_energy',
            field=models.FloatField(default=360),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='base_energy',
            field=models.FloatField(default=72),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='base_energy',
            field=models.FloatField(default=360),
        ),
    ]
