# Generated by Django 5.1.3 on 2025-02-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_house_user_house_landlord_house_owner_guestcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='devices.house'),
        ),
    ]
