# Generated by Django 5.1.3 on 2025-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.FloatField(default=22),
        ),
    ]
