# Generated by Django 5.1.3 on 2025-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_alter_room_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='rgb',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
