# Generated by Django 5.1.3 on 2025-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_light_rgb'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='statusBool',
            field=models.BooleanField(default=False),
        ),
    ]
