# Generated by Django 5.1.3 on 2025-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_device_statusbool'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='extra_energy',
            field=models.FloatField(default=0),
        ),
    ]
