# Generated by Django 5.1.3 on 2025-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_device_extra_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='brightness',
            field=models.IntegerField(default=50),
        ),
    ]
