# Generated by Django 5.1.3 on 2025-02-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_automation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='id',
        ),
        migrations.AddField(
            model_name='automation',
            name='auto_id',
            field=models.AutoField(default=999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
