# Generated by Django 5.1.3 on 2025-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_remove_automation_id_automation_auto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_save',
            field=models.BooleanField(default=False),
        ),
    ]
