# Generated by Django 5.1.3 on 2025-03-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_device_power_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_hat', models.CharField(choices=[('hat0', 'Hat 0'), ('hat1', 'Hat 1'), ('hat2', 'Hat 2'), ('hat3', 'Hat 3'), ('hat4', 'Hat 4'), ('hat5', 'Hat 5'), ('hat6', 'Hat 6'), ('hat7', 'Hat 7'), ('hat8', 'Hat 8'), ('hat9', 'Hat 9')], default='hat0', max_length=10)),
                ('current_bg', models.CharField(choices=[('bg1', 'Background 1'), ('bg2', 'Background 2'), ('bg3', 'Background 3'), ('bg4', 'Background 4'), ('bg5', 'Background 5'), ('bg6', 'Background 6'), ('bg7', 'Background 7'), ('bg8', 'Background 8'), ('bg9', 'Background 9')], default='bg1', max_length=10)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('death', 'Death')], default='happy', max_length=10)),
                ('pending_xp', models.PositiveIntegerField(default=0)),
                ('actual_xp', models.PositiveIntegerField(default=0)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='devices.house', verbose_name='Associated House')),
            ],
            options={
                'verbose_name': 'House Pet',
                'verbose_name_plural': 'House Pets',
            },
        ),
    ]
