# Generated by Django 5.1.3 on 2025-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='unlocked_bgs',
            field=models.JSONField(default=['bg1']),
        ),
        migrations.AddField(
            model_name='pet',
            name='unlocked_hats',
            field=models.JSONField(default=['hat0']),
        ),
        migrations.AlterField(
            model_name='pet',
            name='current_bg',
            field=models.CharField(default='bg1', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='current_hat',
            field=models.CharField(default='hat0', max_length=10),
        ),
    ]
