# Generated by Django 5.1.3 on 2025-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_pet_unlocked_bgs_pet_unlocked_hats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='actual_xp',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
