# Generated by Django 5.1.3 on 2025-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_alter_pet_actual_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
