# Generated by Django 5.1.3 on 2025-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_pet_is_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='death_persisted',
            field=models.BooleanField(default=False),
        ),
    ]
