# Generated by Django 5.1.3 on 2025-03-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_pet_death_persisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermostat',
            name='base_energy',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='fan_speed',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='humidity_level',
        ),
        migrations.AddField(
            model_name='thermostat',
            name='house',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thermostat', to='devices.house'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='thermo_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='mode',
            field=models.CharField(choices=[('Cool', 'Cool'), ('Dry', 'Dry'), ('Fan', 'Fan'), ('Heat', 'Heat')], default='Cool', max_length=4),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='temperature',
            field=models.FloatField(default=22.0),
        ),
    ]
