# Generated by Django 5.1.3 on 2025-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_thermo_delete_thermostat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermo',
            name='mode',
            field=models.CharField(choices=[('Cool', 'Cool'), ('Fan', 'Fan'), ('Heat', 'Heat')], default='Cool', max_length=4),
        ),
    ]
