# Generated by Django 5.1.3 on 2025-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_alter_thermo_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
