# Generated by Django 5.1.3 on 2025-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0034_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
